apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: ${TEMPO_URL}
    uid: tempo
    editable: false
    jsonData:
      httpMethod: GET
      tlsSkipVerify: true
      nodeGraph:
        enabled: true
  
  - name: Loki
    type: loki
    access: proxy
    url: ${LOKI_URL}
    uid: loki
    editable: false
    jsonData:
      maxLines: 1000
      tlsSkipVerify: true
  
  - name: Mimir
    type: prometheus
    access: proxy
    url: ${MIMIR_URL}/prometheus
    uid: mimir
    editable: false
    jsonData:
      httpMethod: GET
      tlsSkipVerify: true